import { permissions } from '../schemas';
import type { SeedContext } from './seed-context';

const platformPermissions = [
  ['platform.tenants.read', 'Ver tenants', 'PLATFORM'],
  ['platform.tenants.create', 'Crear tenants', 'PLATFORM'],
  ['platform.tenants.update', 'Actualizar tenants', 'PLATFORM'],
  ['platform.companies.read', 'Ver companies', 'PLATFORM'],
  ['platform.companies.create', 'Crear companies', 'PLATFORM'],
  ['platform.companies.update', 'Actualizar companies', 'PLATFORM'],
  ['platform.customer_contracts.read', 'Ver contratos de cliente', 'PLATFORM'],
  ['platform.customer_contracts.create', 'Crear contratos de cliente', 'PLATFORM'],
  ['platform.customer_contracts.update', 'Actualizar contratos de cliente', 'PLATFORM'],
  ['platform.internal_customers.create', 'Crear clientes internos', 'PLATFORM'],
  ['platform.users.read', 'Ver usuarios', 'PLATFORM'],
  ['platform.users.create', 'Crear usuarios', 'PLATFORM'],
  ['platform.users.update', 'Actualizar usuarios', 'PLATFORM'],
  ['platform.users.update_credentials', 'Actualizar credenciales de usuario', 'PLATFORM'],
  ['platform.service_clients.read', 'Ver service clients', 'PLATFORM'],
  ['platform.service_clients.create', 'Crear service clients', 'PLATFORM'],
  ['platform.service_clients.update', 'Actualizar service clients', 'PLATFORM'],
  ['platform.service_clients.rotate_secret', 'Rotar secretos de service clients', 'PLATFORM'],
  ['platform.roles.read', 'Ver roles', 'RBAC'],
  ['platform.roles.create', 'Crear roles', 'RBAC'],
  ['platform.roles.update', 'Actualizar roles', 'RBAC'],
  ['platform.roles.assign_permission', 'Asignar permissions a roles', 'RBAC'],
  ['platform.permissions.read', 'Ver permissions', 'RBAC'],
  ['platform.permissions.create', 'Crear permissions', 'RBAC'],
  ['platform.permissions.update', 'Actualizar permissions', 'RBAC'],
  ['platform.memberships.read', 'Ver memberships', 'RBAC'],
  ['platform.memberships.create', 'Crear memberships', 'RBAC'],
  ['platform.memberships.assign_role', 'Asignar roles a memberships', 'RBAC'],
  ['workforce.workers.read', 'Ver trabajadores canonicos', 'WORKFORCE'],
  ['workforce.workers.create', 'Crear trabajadores canonicos', 'WORKFORCE'],
  ['workforce.workers.update', 'Actualizar trabajadores canonicos', 'WORKFORCE'],
  ['workforce.vehicles.read', 'Ver vehiculos canonicos', 'WORKFORCE'],
  ['workforce.vehicles.create', 'Crear vehiculos canonicos', 'WORKFORCE'],
  ['workforce.vehicles.update', 'Actualizar vehiculos canonicos', 'WORKFORCE'],
  ['workforce.worker_assignments.read', 'Ver asignaciones trabajador-empresa', 'WORKFORCE'],
  ['workforce.worker_assignments.create', 'Crear asignaciones trabajador-empresa', 'WORKFORCE'],
  ['workforce.vehicle_assignments.read', 'Ver asignaciones vehiculo-empresa', 'WORKFORCE'],
  ['workforce.vehicle_assignments.create', 'Crear asignaciones vehiculo-empresa', 'WORKFORCE'],
  ['workforce_contracts.contracts.read', 'Ver contratos workforce', 'WORKFORCE_CONTRACTS'],
  ['workforce_contracts.contracts.create', 'Crear contratos workforce', 'WORKFORCE_CONTRACTS'],
  ['workforce_contracts.contracts.update', 'Actualizar contratos workforce', 'WORKFORCE_CONTRACTS'],
  ['workforce_contracts.operational_profiles.read', 'Ver perfiles operacionales workforce', 'WORKFORCE_CONTRACTS'],
  ['workforce_contracts.operational_profiles.create', 'Crear perfiles operacionales workforce', 'WORKFORCE_CONTRACTS'],
  ['workforce_contracts.operational_profiles.update', 'Actualizar perfiles operacionales workforce', 'WORKFORCE_CONTRACTS'],
  ['accreditation.catalog.read', 'Ver catalogo de acreditacion', 'ACCREDITATION'],
  ['accreditation.fulfillments.read', 'Ver cumplimientos de acreditacion', 'ACCREDITATION'],
  ['accreditation.fulfillments.create', 'Registrar cumplimientos de acreditacion', 'ACCREDITATION'],
  ['accreditation.fulfillments.update', 'Actualizar cumplimientos de acreditacion', 'ACCREDITATION'],
  ['accreditation.statuses.read', 'Ver estados de acreditacion', 'ACCREDITATION'],
  ['access_control.installations.read', 'Ver instalaciones de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.installations.create', 'Crear instalaciones de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.installations.update', 'Actualizar instalaciones de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.checkpoints.read', 'Ver checkpoints de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.checkpoints.create', 'Crear checkpoints de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.checkpoints.update', 'Actualizar checkpoints de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.devices.read', 'Ver dispositivos de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.devices.create', 'Crear dispositivos de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.devices.update', 'Actualizar dispositivos de control de acceso', 'ACCESS_CONTROL'],
  ['access_control.events.read', 'Ver eventos de acceso', 'ACCESS_CONTROL'],
  ['access_control.events.create', 'Registrar eventos de acceso', 'ACCESS_CONTROL'],
] as const;

export async function seedPlatformPermissions({ db }: SeedContext) {
  await db
    .insert(permissions)
    .values(
      platformPermissions.map(([slug, displayName, category]) => ({
        slug,
        displayName,
        category,
      })),
    )
    .onConflictDoNothing({
      target: permissions.slug,
    });
}
